version: '3.3'

services:
  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - kong-database:/var/lib/postgresql/data/pgdata

  kong-migrations:
    image: 'kong-jwks'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap && kong migrations up
    restart: on-failure

  kong:
    image: 'kong-jwks'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/cert.pem
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"

  konga:
    image: pantsel/konga
    environment:
      - TOKEN_SECRET=consigmais_secrets
      - DB_HOST=konga-database
      - DB_ADAPTER=mongo
    ports:
      - "1337:1337"


  konga-database:
    image: mongo:3
    volumes:
      - konga-database:/data/db


volumes:
  konga-database:
  kong-database:
